name: moneynote
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.3
  moor: ^3.0.2
  moor_ffi: ^0.5.0
  path_provider:
  path:
  toast: ^0.1.5
  flutter_calendar_carousel: ^1.4.12
  http: ^0.12.1
  intl: ^0.16.1
  flutter_native_splash: ^0.1.9
  flutter_slidable: "^0.5.4"
  scroll_to_index: ^1.0.6
  flutter_launcher_icons: ^0.7.5
  scrollable_positioned_list: ^0.1.8
  font_awesome_flutter: ^8.8.1
  charts_flutter: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  moor_generator: ^3.0.0
  build_runner:

flutter:
  uses-material-design: true
  fonts:
    - family: Exo
      fonts:
        - asset: assets/fonts/Exo-Italic-VariableFont_wght.ttf
    - family: Yomogi
      fonts:
        - asset: assets/fonts/yomogifont.ttf

  assets:
    - assets/image/
    - assets/file/

flutter_native_splash:
  image: "assets/image/money.png"
  color: "2e2e2e"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/launcher.png"

  adaptive_icon_background: "#212121"
  adaptive_icon_foreground: "assets/image/launcher.png"
